//
// Irrlicht Engine Dumper
//

#include "irrlicht_dump.h"
#include "log.h"
#include "xdl.h"
#include <cstdio>
#include <cstring>
#include <dlfcn.h>
#include <vector>
#include <string>

struct SymbolInfo {
    std::string name;
    void *address;
    size_t size;
};

static std::vector<SymbolInfo> symbols;

static void dump_symbols(FILE *file, const char *lib_name) {
    void *handle = xdl_open(lib_name, 0);
    if (!handle) {
        fprintf(file, "// Failed to open %s\n", lib_name);
        LOGW("Failed to open %s for symbol dump", lib_name);
        return;
    }
    
    fprintf(file, "\n// ========================================\n");
    fprintf(file, "// Library: %s\n", lib_name);
    fprintf(file, "// ========================================\n\n");
    
    fprintf(file, "// Library handle: %p\n", handle);
    fprintf(file, "// Symbol lookup skipped to avoid anti-debug detection\n\n");
    
    LOGI("Dumped basic info for %s", lib_name);
}

void irrlicht_dump(const char *output_dir) {
    LOGI("Starting Irrlicht engine dump...");
    
    char dump_path[256];
    snprintf(dump_path, sizeof(dump_path), "%s/irrlicht_dump.txt", output_dir);
    FILE *dump_file = fopen(dump_path, "w");
    if (!dump_file) {
        LOGE("Failed to create dump file: %s", dump_path);
        return;
    }

    fprintf(dump_file, "# Irrlicht Engine Dump\n");
    fprintf(dump_file, "# Generated by Zygisk-IrrlichtDumper\n\n");
    
    // Dump Irrlicht library
    void *irrlicht = xdl_open("libIrrlicht.so", 0);
    if (irrlicht) {
        LOGI("Found libIrrlicht.so");
        fprintf(dump_file, "## Irrlicht Engine Detected\n\n");
        dump_symbols(dump_file, "libIrrlicht.so");
    } else {
        fprintf(dump_file, "## Irrlicht Engine NOT FOUND\n\n");
    }
    
    // Dump CEGUI libraries
    const char *cegui_libs[] = {
        "libCEGUIBase-0.so",
        "libCEGUIIrrlichtRenderer-0.so",
        "libCEGUILuaScriptModule-0.so",
        "libCEGUICoreWindowRendererSet.so",
        "libCEGUITinyXMLParser.so",
        nullptr
    };
    
    fprintf(dump_file, "\n## CEGUI Libraries\n");
    for (int i = 0; cegui_libs[i] != nullptr; i++) {
        void *handle = xdl_open(cegui_libs[i], 0);
        if (handle) {
            LOGI("Found %s", cegui_libs[i]);
            fprintf(dump_file, "- %s: FOUND\n", cegui_libs[i]);
        } else {
            fprintf(dump_file, "- %s: NOT FOUND\n", cegui_libs[i]);
        }
    }
    
    // Dump game library
    fprintf(dump_file, "\n## Game Libraries\n");
    void *yworld = xdl_open("libyworld.so", 0);
    if (yworld) {
        LOGI("Found libyworld.so (game logic)");
        fprintf(dump_file, "- libyworld.so: FOUND (Game Logic)\n");
        dump_symbols(dump_file, "libyworld.so");
    }
    
    // Dump audio libraries
    fprintf(dump_file, "\n## Audio Libraries\n");
    const char *audio_libs[] = {
        "libopenal.so",
        "libogg.so",
        "libvorbis.so",
        nullptr
    };
    
    for (int i = 0; audio_libs[i] != nullptr; i++) {
        void *handle = xdl_open(audio_libs[i], 0);
        if (handle) {
            fprintf(dump_file, "- %s: FOUND\n", audio_libs[i]);
        }
    }
    
    // Dump SDK libraries
    fprintf(dump_file, "\n## SDK and Protection Libraries\n");
    const char *sdk_libs[] = {
        "libBugly-idasc.so",
        "libturingmfa.so",
        "libkycgm.so",
        "libm4399OperateSDKNative.so",
        nullptr
    };
    
    for (int i = 0; sdk_libs[i] != nullptr; i++) {
        void *handle = xdl_open(sdk_libs[i], 0);
        if (handle) {
            fprintf(dump_file, "- %s: FOUND\n", sdk_libs[i]);
        }
    }
    
    fprintf(dump_file, "\n## Analysis Notes\n\n");
    fprintf(dump_file, "### Engine Architecture\n");
    fprintf(dump_file, "- 3D Engine: Irrlicht\n");
    fprintf(dump_file, "- UI System: CEGUI (Crazy Eddie's GUI)\n");
    fprintf(dump_file, "- Script: Lua (via CEGUI Lua module)\n");
    fprintf(dump_file, "- Game Logic: libyworld.so (C++ native code)\n\n");
    
    fprintf(dump_file, "### Reverse Engineering Suggestions\n\n");
    fprintf(dump_file, "1. **Lua Script Analysis**\n");
    fprintf(dump_file, "   - Extract Lua bytecode from APK assets\n");
    fprintf(dump_file, "   - Use unluac or luadec to decompile\n");
    fprintf(dump_file, "   - Hook lua_newstate to capture Lua state\n\n");
    
    fprintf(dump_file, "2. **Native Code Analysis**\n");
    fprintf(dump_file, "   - Analyze libyworld.so with IDA Pro/Ghidra\n");
    fprintf(dump_file, "   - Look for lua_register/luaL_register calls\n");
    fprintf(dump_file, "   - Find game logic functions\n\n");
    
    fprintf(dump_file, "3. **Memory Modification**\n");
    fprintf(dump_file, "   - Hook Lua API functions\n");
    fprintf(dump_file, "   - Modify Lua global variables\n");
    fprintf(dump_file, "   - Inject custom Lua code\n\n");
    
    fprintf(dump_file, "4. **Resource Extraction**\n");
    fprintf(dump_file, "   - Check APK assets folder\n");
    fprintf(dump_file, "   - Look for .lua files\n");
    fprintf(dump_file, "   - Extract CEGUI XML layouts\n");
    fprintf(dump_file, "   - Find Irrlicht scene files\n\n");
    
    fprintf(dump_file, "### Protection Mechanisms\n");
    fprintf(dump_file, "- Bugly: Crash reporting (Tencent)\n");
    fprintf(dump_file, "- Turing MFA: Anti-cheat system\n");
    fprintf(dump_file, "- KYCGM: Possible anti-addiction/real-name verification\n\n");

    fclose(dump_file);
    LOGI("Irrlicht dump completed: %s", dump_path);
}
